//UNIVERSIDAD NACIONAL DE COSTA RICA
//FACULTAD DE CIENCIAS EXACTAS Y NATURALES
//ESCUELA DE INFORMÁTICA
//PROYECTO I DE PROGRAMACIÓN I 
//PROFESORA : KAROL LEITON ARRIETA
//INTEGRANTES: REBECCA GARITA GUTIÉRREZ Y DAVID VILLALOBOS GONZÁLEZ
//II CICLO  DEL 2018
#include "control.h"
int main() {
	control *cont = new control();
	cont->menuPrincipal();
	delete cont;
	return 0;
}