/*			UNIVERSIDAD NACIONAL
FACULTAD DE CIENCIAS EXACTAS Y NATURALES
ESCUELA DE INFORMATICA
PROGRAMACIÓN 1, II PROYECTO
INTEGRANTES:
LUIS DAVID VILLALOBOS GONZÁLEZ
REBECCA GARITA GUTIERREZ
*/
#include "juego.h"
int main() {
	srand(time(NULL));
	juego *scrabble = new juego();
	scrabble->cargar();
	delete scrabble;
}